dist: bionic

os:
    - linux

language:
    - cpp

env:
    - CTEST_OUTPUT_ON_FAILURE=1

before_install:
    - sudo add-apt-repository ppa:mhier/libboost-latest -y
    - sudo apt-get update
    - sudo apt-get install -y libboost1.70-dev
    - which python3

script:
    - mkdir build && cd build
    - cmake ..
    - make -j`nproc`
    - ctest

