sudo: false

os:
    - linux

language:
    - cpp

env:
    - CTEST_OUTPUT_ON_FAILURE=1

script:
    - mkdir build && cd build
    - cmake ..
    - make -j`nproc`
    - make test

addons:
    apt:
        update: true
        sources:
            - sourceline: 'ppa:mhier/libboost-latest'
        packages:
            - cmake
            - boost1.67

