image: Visual Studio 2017

platform:
    - x64

environment:
    BOOST_ROOT: C:/Libraries/boost_1_67_0
    CTEST_OUTPUT_ON_FAILURE: 1

configuration: Release

before_build:
    - cmd: |-
        md build
        cd build
        cmake -G "Visual Studio 15 2017 Win64" -DBOOST_ROOT="%BOOST_ROOT%" -DBoost_USE_STATIC_LIBS=ON ..

build:
    project: build\enyx-net-tools.sln
    verbosity: minimal

test_script:
    - cmd: ctest --build-config %CONFIGURATION%
